# Generated by Django 6.0.4 on 2026-04-23 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_shopcategory_alter_category_options_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True, default='', verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Категорія товарів',
                'verbose_name_plural': 'Категорії товарів',
            },
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='has_plus',
            new_name='is_plus',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_song',
        ),
        migrations.AddField(
            model_name='product',
            name='unlocks_plus',
            field=models.BooleanField(default=False, verbose_name='Відкриває UNIChat Plus'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', verbose_name='Фото профілю'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_song',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Своя пісня'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plus_plan',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='Посилання на фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='live_photo_url',
            field=models.URLField(blank=True, default='', verbose_name='Live photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.productcategory', verbose_name='Категорія'),
        ),
        migrations.DeleteModel(
            name='ShopCategory',
        ),
    ]
