# Generated by Django 6.0.4 on 2026-04-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_productcategory_rename_has_plus_userprofile_is_plus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_file',
            field=models.FileField(blank=True, null=True, upload_to='profile/avatars/', verbose_name='Файл фото профілю'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='live_photo_file',
            field=models.FileField(blank=True, null=True, upload_to='profile/live_photos/', verbose_name='Файл live photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', verbose_name='Фото профілю (старе поле)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='live_photo_url',
            field=models.URLField(blank=True, default='', verbose_name='Live photo (старе поле)'),
        ),
    ]
