# Generated by Django 6.0.4 on 2026-04-24 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order_orderitem_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Підтема', 'verbose_name_plural': 'Підтеми'},
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_messages', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='myapp.comment', verbose_name='Відповідь на повідомлення'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_topics', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.post', verbose_name='Підтема'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.category', verbose_name='Основна тема'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Опис підтеми'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва підтеми'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', verbose_name='Фото профілю старе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='live_photo_file',
            field=models.FileField(blank=True, null=True, upload_to='profile/live_photos/', verbose_name='Live background'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='live_photo_url',
            field=models.URLField(blank=True, default='', verbose_name='Live photo старе'),
        ),
    ]
