# Generated by Django 6.0.4 on 2026-04-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Відповідь', 'verbose_name_plural': 'Відповіді'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Теми'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='Користувач', max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.post', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст відповіді'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Текст теми'),
        ),
    ]
