# Generated by Django 6.0.4 on 2026-04-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_avatar_file_userprofile_live_photo_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='profile/songs/', verbose_name='Файл пісні'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_song',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Назва пісні'),
        ),
    ]
