# Generated by Django 6.0.4 on 2026-04-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='avatar_file',
            field=models.FileField(blank=True, null=True, upload_to='forum/category_avatars/', verbose_name='Аватарка основної теми'),
        ),
        migrations.AddField(
            model_name='comment',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='forum/chat_media/', verbose_name='Фото або відео'),
        ),
        migrations.AddField(
            model_name='post',
            name='avatar_file',
            field=models.FileField(blank=True, null=True, upload_to='forum/topic_avatars/', verbose_name='Аватарка підтеми'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Повідомлення'),
        ),
    ]
