# Generated by Django 6.0.4 on 2026-04-28 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_saveditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='myapp_categ_name_b18f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-created_at'], name='myapp_categ_created_dfcc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='myapp_comme_post_id_d0fcc9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='myapp_comme_author__9c6bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='myapp_comme_parent__bfcc06_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-updated_at'], name='myapp_post_categor_ee453d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='myapp_post_author__70bbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='myapp_post_created_58fa6e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'name'], name='myapp_produ_categor_3ebf8c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['unlocks_plus'], name='myapp_produ_unlocks_b9e4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='myapp_produ_created_e3d47d_idx'),
        ),
        migrations.AddIndex(
            model_name='saveditem',
            index=models.Index(fields=['user', '-created_at'], name='myapp_saved_user_id_776c28_idx'),
        ),
        migrations.AddIndex(
            model_name='saveditem',
            index=models.Index(fields=['post'], name='myapp_saved_post_id_0e3f43_idx'),
        ),
        migrations.AddIndex(
            model_name='saveditem',
            index=models.Index(fields=['comment'], name='myapp_saved_comment_f5dd46_idx'),
        ),
    ]
