# Generated by Django 6.0.4 on 2026-04-28 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_category_myapp_categ_name_b18f9b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Повідомлення')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
            ],
            options={
                'verbose_name': 'Особисте повідомлення',
                'verbose_name_plural': 'Особисті повідомлення',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'receiver', '-created_at'], name='myapp_direc_sender__be1849_idx'), models.Index(fields=['receiver', 'is_read'], name='myapp_direc_receive_1b444a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('accepted', 'Прийнято'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL, verbose_name='Від користувача')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL, verbose_name='До користувача')),
            ],
            options={
                'verbose_name': 'Дружба',
                'verbose_name_plural': 'Дружба',
                'indexes': [models.Index(fields=['from_user', 'status'], name='myapp_frien_from_us_90a75c_idx'), models.Index(fields=['to_user', 'status'], name='myapp_frien_to_user_99395f_idx'), models.Index(fields=['-created_at'], name='myapp_frien_created_feb68f_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
